project:
  type: website

website:
  title: "SEEC Annual Report 2025"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: team.qmd
        text: Team
      - href: students.qmd
        text: Students

format:
  html:
    theme: cosmo
    toc: true
    page-layout: full

execute:
  echo: false
  message: false
  warning: false
  cache: false
